### ISSUE TITLE
Add auto refresh messages on start

### ISSUE THREAD

**Issue by Taz03** [Taz03/Sticky-Bot#9]
when the bot goes offline and starts again it sends a new message after a new message in the channel after starting again, so any message in this gap will be ignored. Make it so that when it starts it sends a new message in each channel despite theres a new message or not, or even better only send if there are new messages.

**Comment by EyadTamer999** [comment]
Where can I start with this issue? where should I look?

**Comment by EyadTamer999** [comment]
Update #1: 
I've been looking through the code for a bit now, and an idea I have is that since the bot can read messages, if the bot goes offline and starts again we can use some kind of flag to tell if for example he's back (we would check old messages and the time the last message was sent) and through that we can make the bot send a new message saying something like "Welcome back users". pretty straight forward I would say.

**Comment by EyadTamer999** [comment]
Note: it would be really good for the bot to keep track of time frames of message last sent and the current time so that the bot doesn't keep on sending the welcoming message over and over.

**Comment by Taz03** [comment]
> Where can I start with this issue? where should I look?

in [StickyMessageUtils.java](https://github.com/Taz03/Sticky-Bot/blob/master/src/main/java/io/github/taz/stickybot/sticky/StickyMessageUtils.java) u see there is an static initializer which puts stuff in the `guildMap` so after that just send a new message u can get the logic from [MessageReceivedListener.java](https://github.com/Taz03/Sticky-Bot/blob/master/src/main/java/io/github/taz/stickybot/listener/MessageReceivedListener.java)

**Comment by Taz03** [comment]
> Update #1: I've been looking through the code for a bit now, and an idea I have is that since the bot can read messages, if the bot goes offline and starts again we can use some kind of flag to tell if for example he's back (we would check old messages and the time the last message was sent) and through that we can make the bot send a new message saying something like "Welcome back users". pretty straight forward I would say.

yes thats the idea, see the demo video in README first if u haven't already. u don't need to flag and stuff heres a little outline how u can do that:-
get a sticked message(here u have the last message id and channel it is sticked in), get the last message in this channel, if the last message and sticked message have different ids send a new sticked message

**Comment by Taz03** [comment]
> Note: it would be really good for the bot to keep track of time frames of message last sent and the current time so that the bot doesn't keep on sending the welcoming message over and over.

we don't send the welcoming message btw, we send the sticked message, ig u didn't get what i mean, watch the demo video first, what it does is send the sticked message after every other message sent in that channel, but now say the bot is offline(for whatever reason) and there are new messages in this channel, and now the issue is fixed on the server and the bot is online again, but there are new messages already after the last sticked message sent by the bot, and bot ignores that, the solution is the bot will send a new message after coming online again, if u still don't get it let me know i'll show u example in discord server

**Comment by EyadTamer999** [comment]
Yea I would appreciate a video showing the issue.

**Comment by Taz03** [comment]
https://user-images.githubusercontent.com/73871477/211378628-f2b459e0-c849-4e52-b83b-349647460b72.mp4

@EyadTamer999 here is a video showing the problem
